# CNB 流水线配置 - Docker 镜像同步
# 文档: https://docs.cnb.cool/zh/artifact/docker.html

# ============================================================
# 1. Git 推送自动触发 - 同步 docker-images.txt 中的所有镜像
# ============================================================
avwq_dev:
  push:
    - services:
        - docker
      env:
        CNB_ORG: avwq
        CNB_PROJECT: soucod/official-images
      stages:
        - name: 同步所有镜像
          script: |
            chmod +x .cnb/scripts/*.sh
            ./.cnb/scripts/sync-from-file.sh docker-images.txt --arch amd64

# ============================================================
# 2. 手动触发 - 同步单个镜像 (由 .cnb/web_trigger.yml 按钮触发)
# ============================================================
sync_single_image:
  web_trigger:
    - services:
        - docker
      env:
        CNB_ORG: avwq
        CNB_PROJECT: soucod/official-images
      stages:
        - name: 同步指定镜像
          script: |
            chmod +x .cnb/scripts/*.sh
            echo "同步镜像: ${IMAGE_NAME}:${IMAGE_TAG:-latest}"
            echo "平台: ${IMAGE_PLATFORM:-docker.io}"
            echo "架构: ${IMAGE_ARCH:-amd64}"
            ./.cnb/scripts/sync-image.sh "${IMAGE_NAME}:${IMAGE_TAG:-latest}" \
              --platform "${IMAGE_PLATFORM:-docker.io}" \
              --arch "${IMAGE_ARCH:-amd64}"

# ============================================================
# 3. 手动触发 - 同步所有镜像
# ============================================================
sync_all_images:
  web_trigger:
    - services:
        - docker
      env:
        CNB_ORG: avwq
        CNB_PROJECT: soucod/official-images
      stages:
        - name: 同步全部镜像
          script: |
            chmod +x .cnb/scripts/*.sh
            ./.cnb/scripts/sync-from-file.sh docker-images.txt --arch "${SYNC_ARCH:-amd64}"

# ============================================================
# 4. 手动触发 - 同步指定文件中的镜像
# ============================================================
sync_from_custom_file:
  web_trigger:
    - services:
        - docker
      env:
        CNB_ORG: avwq
        CNB_PROJECT: soucod/official-images
      stages:
        - name: 同步指定文件中的镜像
          script: |
            chmod +x .cnb/scripts/*.sh
            FILE_PATH="${CUSTOM_FILE:-docker-images.txt}"
            if [ ! -f "$FILE_PATH" ]; then
              echo "错误: 文件不存在: $FILE_PATH"
              exit 1
            fi
            ./.cnb/scripts/sync-from-file.sh "$FILE_PATH" --arch "${SYNC_ARCH:-amd64}"

# ============================================================
# 5. 手动触发 - 同步 library 单个镜像最新版本
# ============================================================
sync_library_image:
  web_trigger:
    - services:
        - docker
      env:
        CNB_ORG: avwq
        CNB_PROJECT: soucod/official-images
      stages:
        - name: 同步 library 镜像
          script: |
            chmod +x .cnb/scripts/*.sh
            echo "同步 library 镜像: ${LIB_IMAGE_NAME}"
            echo "版本数量: ${VERSION_COUNT:-5}"
            echo "架构: ${SYNC_ARCH:-amd64}"
            ./.cnb/scripts/sync-library.sh "${LIB_IMAGE_NAME}" \
              --versions "${VERSION_COUNT:-5}" \
              --arch "${SYNC_ARCH:-amd64}"

# ============================================================
# 6. 手动触发 - 同步 library 全部镜像
# ============================================================
sync_library_all:
  web_trigger:
    - services:
        - docker
      env:
        CNB_ORG: avwq
        CNB_PROJECT: soucod/official-images
      stages:
        - name: 同步全部 library 镜像
          script: |
            chmod +x .cnb/scripts/*.sh
            echo "同步全部 library 镜像"
            echo "版本数量: ${VERSION_COUNT:-5}"
            echo "架构: ${SYNC_ARCH:-amd64}"
            ./.cnb/scripts/sync-library.sh --all \
              --versions "${VERSION_COUNT:-5}" \
              --arch "${SYNC_ARCH:-amd64}"
